language: node_js
node_js:
  - node

# https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
addons:
  apt:
    packages:
      - xvfb
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # Install yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install: yarn install

script:
  - npm run build:production
  - npm test
  - npm run test:api

after_success:
  - npm run coveralls
  - bash bin/deploy.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages

notifications:
  webhooks: http://webhook.hakatashi.com/travis
